project_id                   = "graceful-fact"
region                       = "australia-southeast1"
zone                         = "australia-southeast1-a"
artifact_registry_repository = "web-app-docker"
gke_cluster                  = "web-app-cluster"
gke_cluster_node_pool        = "web-app-node-pool"
network_name                 = "vpc-network"
subnetwork_name              = "vpc-subnetwork"