name: CI/CD Pipeline

on:
  push:
    branches:
      - development

env:
  GCP_PROJECT: graceful-fact
  IMAGE_NAME: web-app-image
  GKE_CLUSTER: autopilot-cluster-1
  GKE_REGISTRY: web-app-docker
  GCR_ZONE: australia-southeast1  # Change to your region, e.g., 'us', 'eu', or 'asia'
  GITHUB_SHA: ${{ github.sha }}
  K8S_NAMESPACE: default  # Kubernetes namespace
  HELM_RELEASE_NAME: web-app-dev  # Helm release name

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # # Authenticate GitHub Actions with Google Cloud
      # - name: Setup Google Cloud Authentication 
      #   uses: 'google-github-actions/auth@v2'
      #   with:
      #     credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      # - name: Configure Docker to use gcloud as a credential helper
      #   run: gcloud auth configure-docker $GCR_ZONE-docker.pkg.dev

      # - name: Build Docker Image
      #   run: |
      #     cd web-app && docker build -t $GCR_ZONE-docker.pkg.dev/$GCP_PROJECT/$GKE_REGISTRY/$IMAGE_NAME:$GITHUB_SHA .

      # - name: Push Docker Image to GCR
      #   run: |
      #     cd web-app && docker push $GCR_ZONE-docker.pkg.dev/$GCP_PROJECT/$GKE_REGISTRY/$IMAGE_NAME:$GITHUB_SHA

  deploy:
    name: Deploy to GKE with Helm
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Authenticate GitHub Actions with Google Cloud
      - name: Setup Google Cloud Authentication 
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: GKE Auth Plugin Installation
        run: |
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -          sudo apt-get install google-cloud-cli-gke-gcloud-auth-plugin
          sudo apt-get update && sudo apt-get install google-cloud-cli
          sudo apt-get install google-cloud-sdk-gke-gcloud-auth-plugin
          
      - name: Connect to GKE Cluster
        run: |
          gcloud container clusters get-credentials autopilot-cluster-1 --region us-central1 --project graceful-fact
      
      - name: Deploy with Helm
        run: |
          helm upgrade --install $HELM_RELEASE_NAME ./helm/web-app \
            --namespace $K8S_NAMESPACE \
            --set image.repository=$GCR_ZONE-docker.pkg.dev/$GCP_PROJECT/$IMAGE_NAME \
            --set image.tag=${{ github.sha }}
